version: "3.8"
services:
  web:
    container_name: alloy
    build: .
    env_file: ./.env
    ports:
      - "80:${PORT}"
    links:
      - mongo
    restart: always
  mongo:
    container_name: mongo_db
    image: mongo